server:
  port: 8082

spring:
  application:
    name:
      webflux

ms-config:
  datasource:
    r2dbpostgrest:
      driver: postgresql
      host: testpostgrest.postgres.database.azure.com
      port: 5432
      username: testadmin
      password: Admin1234
      database: postgres
      poolinitialSize: 10
      poolmaxSize: 20

